    DROP TABLE IF EXISTS user;
    CREATE TABLE user (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    user_name VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL
    );